Repository dakota-bruffett/Project_3_Apis, pull requests merged in 2023-10, with the labels that each got.

#14 Revert "Main not name"
  .idea/misc.xml
  app.py
  databases/Music.db.py
Labels: bug

#8 Created a Spotify API module and edited app.py to take in spotify api…
  .gitignore
  app.py
  artistAPI.py
  spotifyAPI.py
  templates/artist.html
Labels: enhancement

#33 Added top tracks information to display on the artists.html, as well …
  app.py
  spotifyAPI.py
  static/style.css
  templates/artist.html
  templates/index.html
  youtube_api.py
Labels: enhancement

#34 Fixed logging to display the api keys on terminal on Spotify.api
  spotifyAPI.py
Labels: documentation

#35 Added a .env example file to copy for other team members. Teamates ca…
  .env.example
  .gitignore
  spotifyAPI.py
Labels: bug, documentation, enhancement

#42 Fixed issue with decouple library is not reading env variables correc…
  .env.example
  spotifyAPI.py
  youtube_api.py
Labels: bug, documentation

#47 YouTube API module improved error handling PR
  app.py
  youtube_api.py
Labels: enhancement

#46 Merge (Database saving feature)
  databases/Music.db.py
Labels: bug, enhancement

#48 2 tests for spotify api module. Testing for gateway functonality to …
  test_Spotify_API.py
Labels: documentation, enhancement

#60 Program Cleanup PR
  Tests/test_Spotify_API.py
  youtube_api.py
Labels: enhancement

#55 README update
  README.md
Labels: enhancement

#58 Updated the .env example file with correct instructions
  .env_example
Labels: enhancement

#61 Requirements
  databases/Requirements
  requirements.txt
Labels: documentation

#63 Fixed logic for Spotify access token
  spotifyAPI.py
Labels: bug
